"""
Django settings for transitions project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# from django.middlewares.security import SecurityMiddleware

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$1k4cs066^_qi8f&7ah$9zl7unw+poznr-l*yio!uz(^2%-+m)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SITE_ID=1
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'oauth2_provider',
    'django.contrib.staticfiles',
    'transitions.Project',
    'corsheaders',
    'rest_framework.authtoken',
    'rest_framework',
    'debug_toolbar',
    'django_filters',
    'social_django',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'transitions.Project.middlewares.SimpleMiddlewares.SimpleLogMiddleware',
]

ROOT_URLCONF = 'transitions.urls'
INTERNAL_IPS = [
    '127.0.0.1',
]

CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_ALL_ORIGIN = True
# ALLOWED_HOSTS
# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:3000"
# ]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transitions.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':[
        # 'transitions.Project.helper.permission.IsPermission',
        'rest_framework.permissions.IsAuthenticated',
     ],
     'DEFAULT_AUTHENTICATION_CLASSES':[

         'transitions.Project.helper.Oauth2.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication', # To keep the Browsable API
        # 'transitions.Project.helper.authentic.IsAuth',
        # 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
     ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',

}
OAUTH_PROVIDER=(

)
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
USER_METHOD = ("POST","GET")
CUSTOMER_METHOD = ("POST","GET","DELETE","PUT")
STATIC_URL = '/static/'
OAUTH_BASE_URL = 'https://asg-oauth2.appspot.com/'
URL_MESSAGE = "https://masking.zenziva.net/api/sendsms/"
URL_WHATSAPP = "https://waba.damcorp.id/whatsapp/"
TOKEN_WHATSAPP = ""
USERKEY = ""
PASSKEY = ""
IMAP_USER = ""
IMAP_PASSWORD = ""
IMAP_SERVER = ""
SMTP_ADDRESS = ""