# Generated by Django 3.1.1 on 2020-12-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeremail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customermessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
    ]
