# Generated by Django 3.1.1 on 2020-12-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20201207_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeremail',
            options={'permissions': (('can_add_customer_email', 'Can add customer email'), ('can_view_customer_email', 'Can view customer email'), ('can_change_customer_email', 'Can change customer email'), ('can_delete_customer_email', 'Can delete customer email'))},
        ),
        migrations.AlterModelOptions(
            name='customermessage',
            options={'permissions': (('can_add_customer_message', 'Can add customer message'), ('can_view_customer_message', 'Can view customer message'), ('can_change_customer_message', 'Can change customer message'), ('can_delete_customer_message', 'Can delete customer message'))},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'permissions': (('can_add_customer_template', 'Can add customer template'), ('can_view_customer_template', 'Can view customer template'), ('can_change_customer_template', 'Can change customer template'), ('can_delete_customer_template', 'Can delete customer template'))},
        ),
    ]
